import sys
from authentication import getSession
import urllib.parse
import json
import akari

org_ids = sys.argv

session = getSession()

screen_names = ['oti_ryo',
  'tackey_king',
  'Py0Ri',
  'rama5296',
  'platypus___',
  'shokoofficial1',
  'momo55362293',
  'catwalk_mizoo',
  'nikukyu0834',
  'ararearare4',
  'jasumin___01',
  'macoto_toiro',
  'pika_meg',
  'yuulog_com',
  'sayomamas',
  'niinaafi',
  'A_yeah_088',
  'with__pennylane',
  'haruhiko_yb',
  'tsugumi_tsugu3',
  '3pei_tw',
  'kinako_1988',
  'mama_mental106',
  'Masatoinfinity',
  'inouway318',
  'Koheipapa25',
  'shenamon_blog',
  'shykaeru',
  'hitujin03',
  'hiromisunny',
  'hiromaru5602',
  'kaco_matsu',
  'amashinkun_papa',
  'piroisaikata',
  'tabi_jurico',
  'MimosaSuzu',
  'akhihik',
  '55mamalog',
  'mina_jovo',
  'Snow4mama',
  'nicoTrip87',
  'YURAmarie',
  'yukko_s17',
  'sayaka55happy',
  'ug823053',
  'wone7139',
  'happcolo',
  'mu_mi_inaka',
  'kemcy15',
  'hukurohukuhuku',
  'chimney_224',
  'shoko92111',
  'mamako_blog',
  'niko_gutaratuma',
  'dynamic_ninjya',
  'miyumam2525',
  'zubora_tsuma',
  'buttiandi',
  'DRPooh7',
  'ari__kakei',
  'tomo_cocolife',
  'mumumu_shi',
  'tsubatin8030',
  'kurogomahan',
  'keiko720',
  'metabonaruikun7',
  'mihoko44328404',
  'indigoblue1210',
  'yo_hp100',
  'sawasai3831',
  'k_kazusa0415',
  'fujifujimax',
  'chan52pp',
  'uhtan9',
  'r_chiyoko',
  'daijiro_takeuch',
  'hans217',
  'rikocal',
  'bimboooo_family',
  'uOmG0YOxbJjyVDk',
  'sakabou2',
  'usg113bkw',
  'mi1990yen',
  'Im_Negan422x_4',
  'lifeworkshare',
  'makico_doconico',
  'onepipst',
  'chanpii1331',
  ' conayuki_nanibl',
  'conamin1',
  'UBlog2020',
  'mizu_0w0_',
  'KetumeKoki',
  '3dango_saty',
  'okeguchisan',
  'rihojiro1',
  'matsusawako',
  'takesodaddy',
  'kyoukastyle',
  'riutiu',
  '7rtXrp',
  'obarico_fight',
  'sunny424u',
  '3939_LS',
  'HATAPATA3',
  'mi_tuuu',
  'nico_life358',
  'hide3_ZeroMeil',
  'pomme23',
  'tabizukimaki',
  'sakai150150',
  'ukky_blog',
  'maeshioshizuku',
  'bowbow_mama',
  'chiyuki3030',
  'asim1101110403',
  'Kitchen_sneaker',
  'yukko_sensei',
  'misao53522177',
  'kotoankey',
  '2boysmama1',
  'h_kafka',
  'm22m22x',
  'tamalog33']

api_url = 'https://api.twitter.com/1.1/friendships/create.json'
for screen_name in screen_names:
  params = {
    'screen_name' : screen_name,
    'follow' : True
  }
  session.post(api_url, params = params)
